news_portal/blog/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (PostsList, PostDetail, SearchPosts,
                    ArticleCreate, ArticleUpdate, ArticleDelete,
                    NewsCreate, NewsUpdate, NewsDelete,
                    news_redirect,
                    CategoryListView, subscriptions, upgrade_me, subscribe )

from .views import new_add
from django.contrib import admin


app_name='blog'

urlpatterns = [
    path('', news_redirect),
    path('news/', PostsList.as_view(), name='posts_list'),
   # path('account/login/', LoginView.as_view(), name='login'),
    path('news/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('search/', SearchPosts.as_view(), name='search_posts'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', NewsUpdate.as_view(), name='news_update'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/create/', ArticleCreate.as_view(), name='article_create'),
    path('articles/<int:pk>/edit/', ArticleUpdate.as_view(), name='article_update'),
    path('articles/<int:pk>/delete/', ArticleDelete.as_view(), name='article_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    # path('add/', new_add)
    # path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    # path('categories/<int:pk>'/subscribe, subscribe, name='subscribe')
]

news_portal/news_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('blog.urls', namespace='blog')),
]

news_portal/templates/category_list.html
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
<div class="col-lg-12 text-center">
    <h1>Все посты</h1>
    {% if is_not_subscriber %}
    <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
{% if is_not_subscriber %}
    <hr>
    <ul class="list-group list-group-flush">
<!--{% block content %}-->
<!--<h1 class="text-center">Новости<span class="=text-muted fs-6 fw-normal">Всего: {{ page_obj_paginator.count }}</span></h1>-->
<!--    {% if is_not_subscriber %}-->
<!--        <p class="=text-center"><a href="{% | %}" class="=btn btn-secondary btn-sm">Подписаться</a></p>-->
<!--    {% endif %}-->

news_portal/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Django - news portal</title>

    {% load static %}
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>

<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">Добро пожаловать в Новостной портал</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
           <ul class="navbar-nav ml-auto">
               <li class="nav-item"> <a class="nav-link" href="/news/">Все посты</a></li>
               <li class="nav-item"> <a class="nav-link" href="/admin/">Админка</a></li>
               <li class="nav-item"> <a class="nav-link" href="{% url 'blog:search_posts' %}">Поиск</a></li>
               <li class="nav-item"> <a class="nav-link" href="/articles/create/">Добавить статью</a></li>
               <li class="nav-item"> <a class="nav-link" href="/news/create/">Добавить Новость</a></li>
               {% if user.is_authenticated %}
               <li class="nav-item"> <a class="nav-link" href="/accounts/logout/">Выйти</a></li>
               <!-- Добавить здесь новые пункты меню. -->
               <li class="nav-item"> <a class="nav-link" href="/subscriptions/">Пользователь: {{ user.username }}</a></li>
               {% else %}
               <li class="nav-item"> <a class="nav-link" href="/accounts/login/">Войти</a></li>
               <li class="nav-item"> <a class="nav-link" href="/accounts/signup/">Регистрация</a></li>
               {% endif %}
           </ul>


       </div>
   </div>
</nav>

<!-- Page content-->
<div class="container">
    <div class="row">
            {% block content %}
            {% endblock content %}
    </div>
</div>
</body>
</html>

news_portal/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">Авторизация</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       </nav>
       <br>

    <form method="post">
      {% csrf_token %}
      <table>
        {{ form.as_p }}
        <tr>
          <td>&nbsp;</td>
          <td><input type="submit" value="Войти"></td>
        </tr>
      </table>
    </form>
</body>
</html>

news_portal/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выход</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">Вы вышли из системы</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       </nav>
</body>
</html>

news_portal/templates/main.html
<html>
    <head>
        <title> Order board</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Order board</a></h1>
        </div>
        <div>
            <button> <a href=""> Добавить заказ </a> </button>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

news_portal/templates/post.html
<!--  наследуемся от шаблона default.html -->
{% extends 'default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице выводим пост, идентификатор которого был передан в url -->
{% block content %}
<div class="row justify-content-center">
<div class="card col-8 my-4">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Дата публикации: {{ post.date_time }}</h6>
    <p class="card-text">{{ post.text|censor }}</p>
    <a href="/news/" class="card-link">К списку статей...</a>
  </div>
</div>
</div>
{% endblock content %}

news_portal/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Новая статья <a href="{{ link }}">Статья</a> в твоем разделе! </h2>
<p>{{ text }}</p>
</body>
</html>

news_portal/templates/post_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем запись с заголовком "{{ object.title }}"?</p>
    <input type="submit" value="Delete" class="btn btn-danger"/>
    <a class="btn btn-secondary" role="button" href="{{ previous_page_url }}">Cancel</a>
</form>
{% endblock content %}

news_portal/templates/post_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>{{ page_title }}</h1>

<form action="" method="post" class="my-4">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="btn btn-primary"/>
    <a class="btn btn-outline-danger" role="button" href="{{ request.path }}">Очистить </a>
</form>
{% endblock content %}

news_portal/templates/posts.html
<!--  наследуемся от шаблона default.html -->
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
<div class="col-lg-12 text-center">
    <h1>Все посты</h1>
    <h3>Всего постов: {{ posts|length }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Дата публикации</th>
            <th scope="col">Текст</th>
            <th scope="col">Ссылка на статью</th>
            <th scope="col">Редактировать</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row">{{ post.title }}</th>
            <td>{{ post.date_time }}</td>
            <td>{{ post.text | truncatewords:20 | censor}}</td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}">Читать</a></td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/edit/">Редактировать</a></td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/delete/">Удалить</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{# Пагинация на странице #}
<hr class="mt-4">

<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{% url_replace page=1 %}">1</a></li>
                {% if page_obj.previous_page_number != 1 %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
               {% endif %}
            {% endif %}

            <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
               {% endif %}
                {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}

news_portal/templates/product_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

news_portal/templates/search.html
<!--  наследуемся от шаблона default.html -->
{% extends 'default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице выводим форму поиска постов. -->
{% block content %}

{# Форма фильтра 'PostFilter' #}
    <form action="" method="GET">
        {# Переменная, которую мы передали через контекст, может сгенерировать форму с полями #}
        {{ search_filter.form.as_p }}
        <input type="submit" value="Найти" class="btn btn-success"/>
        <a class="btn btn-secondary" role="button" href="{{ request.path }}">Сбросить фильтры</a>
    </form>

<div class="col-lg-12 text-center">
    <h1>Все посты</h1>
    <h3>Всего постов: {{ posts|length }}</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Заголовок</th>
            <th scope="col">Дата публикации</th>
            <th scope="col">Текст</th>
            <th scope="col">Ссылка на статью</th>
            <th scope="col">Редактировать</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row">{{ post.title }}</th>
            <td>{{ post.date_time }}</td>
            <td>{{ post.text | truncatewords:20 | censor}}</td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}">Читать</a></td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/edit/">Редактировать</a></td>
            <td><a class="btn btn-primary btn-sm" href="/news/{{ post.pk }}/delete/">Удалить</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{# Пагинация на странице #}
<hr class="mt-4">

<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{% url_replace page=1 %}">1</a></li>
                {% if page_obj.previous_page_number != 1 %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
               {% endif %}
            {% endif %}

            <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
               {% if paginator.num_pages != page_obj.next_page_number %}
                   <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                   <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
               {% endif %}
                {% endif %}
        </ul>
    </nav>
</div>

{% endblock content %}

news_portal/templates/signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>

       <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
   <div class="container">
       <a class="navbar-brand" href="#">Регистрируемся</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse"
               data-target="#navbarResponsive"
               aria-controls="navbarResponsive" aria-expanded="false"
               aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       </nav>
<br>
<form method="post">
    {% csrf_token %}

    {% for field in form %}
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
        <span>*</span>
        {% endif %}
    </label>
    <p>{{ field.help_text }}</p>
    <p> {{ field }}</p>
    {% endfor %}
    <p><input type="submit" value="Зарегистрироваться"></p>
</form>
</body>
</html>

news_portal/templates/subscriptions.html
{% extends 'default.html' %}
{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}"/>
                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                    <a>
                {% endif %}
            </form>
        </p>

    {% endfor %}
{% endblock content %}